# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: WebSockets Repro
version: 0.1.3
slug: websockets-repro
description: WebSocket Supervisor Reproduction add-on
url: https://github.com/felipecrs/websockets-supervisor-repro
arch:
  - amd64
  - aarch64
init: false
ingress: true
ingress_port: 8000
panel_icon: mdi:table-tennis
ports:
  8000/tcp: 8000
